spring:
  application:
    name: warehouse-service

server:
  port: 8082

app:
  version: 0.0.1-SNAPSHOT

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
