apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airops360
resources:
  - namespace.yaml
  - app-config.yaml
  - flight-service.yaml
  - cargo-service.yaml
  - warehouse-service.yaml
  - inventory-service.yaml
  - baggage-service.yaml
  - simulator-service.yaml
  - api-gateway.yaml
  - operations-dashboard.yaml
